#!/bin/bash

if [ -z "$RUBYGEMS_API_KEY" ]; then
  echo "Error: must provide RUBYGEMS_API_KEY" >&2
  exit 1
fi

echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > $HOME/.gem/credentials
chmod 0600 $HOME/.gem/credentials
gem push terraorg-*.gem
