#!/bin/bash

if [ -z "$GITHUB_TOKEN" ]; then
  echo "Error: must provide GITHUB_TOKEN" >&2
  exit 1
fi

echo ":github: Bearer $GITHUB_TOKEN" > $HOME/.gem/credentials
chmod 0600 $HOME/.gem/credentials
gem push --key github --host https://rubygems.pkg.github.com/joshk0 terraorg-*.gem
